# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8473c6e7af3425275108fe2118271419a10e3b040489cf99c38562a1e78c5ae1af19601573d0d6b48a12afd4c765b042e052089f7780641475e3ca5f40cf4266

test:
  secret_key_base: f90c51ab8037f271adf455683942761115c1beda6d840dc74d193e7af08fb7ea37f9ad3bc9631d7a669a63b9a3eb4598721cbd0e6af96ff8880e7cbe444da14c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
